'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Check, ExternalLink, LayoutDashboard, Mail, Plus, Save, Settings2, Trash2, UserRound, X } from 'lucide-react'
import { defaultProfile, defaultProjects, defaultSocials, type Profile, type Project, type Social } from '@/lib/data'

const STORE = 'ishan-portfolio-v1'
type Store = { profile: Profile; projects: Project[]; socials: Social[] }
const initial: Store = { profile: defaultProfile, projects: defaultProjects, socials: defaultSocials }

export default function Dashboard() {
  const [data, setData] = useState<Store>(initial)
  const [tab, setTab] = useState<'overview'|'profile'|'projects'|'socials'>('overview')
  const [saved, setSaved] = useState(false)
  const [editing, setEditing] = useState<string | null>(null)
  useEffect(() => { try { const raw = localStorage.getItem(STORE); if (raw) setData(JSON.parse(raw)) } catch {} }, [])
  const save = (next = data) => { localStorage.setItem(STORE, JSON.stringify(next)); setData(next); setSaved(true); setTimeout(() => setSaved(false), 1600) }
  const project = useMemo(() => data.projects.find(p => p.id === editing), [data.projects, editing])

  function addProject() {
    const p: Project = { id: crypto.randomUUID(), title: 'New project', description: 'Add a concise project description.', tech: ['Next.js'], features: ['Add a feature'], year: String(new Date().getFullYear()), accent: 'lime', liveUrl: '#', githubUrl: '#' }
    const next = { ...data, projects: [p, ...data.projects] }; setData(next); setEditing(p.id); save(next)
  }
  function removeProject(id: string) { const next = {...data, projects: data.projects.filter(p => p.id !== id)}; save(next); if (editing === id) setEditing(null) }
  function updateProject(p: Project) { const next = {...data, projects: data.projects.map(x => x.id === p.id ? p : x)}; save(next) }
  function updateProfile(field: keyof Profile, value: string | string[]) { setData(d => ({...d, profile: {...d.profile, [field]: value}})) }
  function updateSocial(id: string, field: keyof Social, value: string) { setData(d => ({...d, socials: d.socials.map(s => s.id === id ? {...s, [field]: value} : s)})) }

  const nav = [
    ['overview', 'Overview', LayoutDashboard], ['profile', 'Profile', UserRound], ['projects', 'Projects', Settings2], ['socials', 'Social links', ExternalLink]
  ] as const

  return <div className="min-h-screen bg-[#f4f4f0] text-[#111]">
    <aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-black/10 bg-white p-5 md:block"><div className="flex h-full flex-col"><div className="mb-10 flex items-center justify-between"><Link href="/" className="font-display text-2xl font-bold">IT<span className="text-[#8cae28]">.</span></Link><span className="rounded-full bg-[#b7f23d] px-2 py-1 text-[10px] font-bold uppercase">Admin</span></div><nav className="space-y-1">{nav.map(([id,label,Icon]) => <button key={id} onClick={() => setTab(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold ${tab === id ? 'bg-black text-white' : 'hover:bg-black/5'}`}><Icon size={18}/>{label}</button>)}</nav><div className="mt-auto rounded-2xl bg-[#f4f4f0] p-4"><p className="text-xs font-bold uppercase tracking-wider text-neutral-400">Live site</p><Link href="/" className="mt-2 flex items-center gap-2 text-sm font-bold">View portfolio <ArrowLeft className="rotate-180" size={15}/></Link></div></div></aside>

    <main className="md:pl-64"><div className="sticky top-0 z-40 flex items-center justify-between border-b border-black/10 bg-[#f4f4f0]/90 px-5 py-4 backdrop-blur md:px-10"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-neutral-400">Portfolio CMS</p><h1 className="mt-1 text-xl font-bold">{nav.find(n => n[0] === tab)?.[1]}</h1></div><div className="flex items-center gap-3"><Link href="/" className="hidden rounded-full border border-black/10 bg-white px-4 py-2 text-sm font-bold md:flex">View site</Link><button onClick={() => save()} className="inline-flex items-center gap-2 rounded-full bg-black px-4 py-2 text-sm font-bold text-white">{saved ? <Check size={16}/> : <Save size={16}/>} {saved ? 'Saved' : 'Save changes'}</button></div></div>

    <div className="border-b border-black/10 bg-white px-5 py-3 md:hidden"><div className="flex gap-2 overflow-x-auto">{nav.map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${tab === id ? 'bg-black text-white' : 'bg-[#f4f4f0]'}`}>{label}</button>)}</div></div>

    <div className="mx-auto max-w-6xl p-5 md:p-10">
      {tab === 'overview' && <Overview data={data} setTab={setTab}/>} 
      {tab === 'profile' && <ProfileEditor profile={data.profile} updateProfile={updateProfile} save={() => save()}/>} 
      {tab === 'projects' && <ProjectsEditor projects={data.projects} editing={editing} project={project} setEditing={setEditing} addProject={addProject} removeProject={removeProject} updateProject={updateProject}/>} 
      {tab === 'socials' && <SocialEditor socials={data.socials} updateSocial={updateSocial} save={() => save()}/>} 
    </div></main>
  </div>
}

function Overview({ data, setTab }: { data: Store; setTab: (x:any)=>void }) { return <div className="space-y-7"><div className="grid gap-5 md:grid-cols-3"><Stat n={String(data.projects.length).padStart(2,'0')} label="Projects"/><Stat n={String(data.profile.skills.length).padStart(2,'0')} label="Skills"/><Stat n={String(data.socials.length).padStart(2,'0')} label="Social links"/></div><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl border border-black/10 bg-white p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-neutral-400">Profile snapshot</p><h2 className="mt-2 font-display text-4xl font-bold">{data.profile.name}</h2><p className="mt-1 text-neutral-500">{data.profile.role} · {data.profile.location}</p></div><button onClick={() => setTab('profile')} className="rounded-full bg-black px-4 py-2 text-xs font-bold text-white">Edit</button></div><div className="mt-7 flex gap-5"><Image src="/profile.png" width={110} height={110} alt="Profile" className="h-28 w-28 rounded-2xl object-cover"/><p className="max-w-xl text-sm leading-7 text-neutral-600">{data.profile.bio}</p></div></section><section className="rounded-3xl border border-black/10 bg-[#b7f23d] p-7"><Sparkle/><p className="mt-8 text-xs font-bold uppercase tracking-[.18em]">Quick action</p><h2 className="mt-2 font-display text-4xl font-bold">Keep the work fresh.</h2><p className="mt-3 text-sm leading-6">Your dashboard edits are reflected on the public portfolio instantly in this browser.</p><button onClick={() => setTab('projects')} className="mt-7 rounded-full bg-black px-5 py-3 text-sm font-bold text-white">Manage projects →</button></section></div><section className="rounded-3xl border border-black/10 bg-white p-7"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-neutral-400">Featured projects</p><h2 className="mt-1 text-2xl font-bold">Your current portfolio</h2></div><button onClick={() => setTab('projects')} className="text-sm font-bold underline">Edit all</button></div><div className="divide-y divide-black/10">{data.projects.map(p => <div key={p.id} className="flex items-center justify-between py-4"><div><p className="font-bold">{p.title}</p><p className="text-sm text-neutral-500">{p.tech.join(' · ')}</p></div><span className="rounded-full bg-[#f4f4f0] px-3 py-1 text-xs font-bold">{p.year}</span></div>)}</div></section></div> }
function Sparkle(){return <div className="flex h-11 w-11 items-center justify-center rounded-full bg-black text-[#b7f23d]"><span>✦</span></div>}
function Stat({n,label}:{n:string;label:string}){return <div className="rounded-3xl border border-black/10 bg-white p-6"><div className="font-display text-5xl font-bold">{n}</div><div className="mt-3 text-sm font-bold text-neutral-500">{label}</div></div>}

function ProfileEditor({ profile, updateProfile, save }: { profile: Profile; updateProfile: (f:keyof Profile,v:any)=>void; save:()=>void }) { return <div className="grid gap-6 lg:grid-cols-[1fr_.4fr]"><section className="rounded-3xl border border-black/10 bg-white p-7"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-neutral-400">Public profile</p><h2 className="mt-1 text-2xl font-bold">Edit your details</h2></div><div className="grid gap-5 md:grid-cols-2"><Field label="Name" value={profile.name} onChange={v=>updateProfile('name',v)}/><Field label="Role" value={profile.role} onChange={v=>updateProfile('role',v)}/><Field label="Location" value={profile.location} onChange={v=>updateProfile('location',v)}/><Field label="Email" value={profile.email} onChange={v=>updateProfile('email',v)}/><Field label="Phone" value={profile.phone} onChange={v=>updateProfile('phone',v)}/><Field label="Availability" value={profile.availability} onChange={v=>updateProfile('availability',v)}/></div><label className="mt-5 block text-sm font-bold">Bio<textarea value={profile.bio} onChange={e=>updateProfile('bio',e.target.value)} rows={6} className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f8f8f5] p-4 outline-none focus:border-black"/></label><label className="mt-5 block text-sm font-bold">Skills <span className="font-normal text-neutral-400">(comma separated)</span><input value={profile.skills.join(', ')} onChange={e=>updateProfile('skills',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))} className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f8f8f5] p-4 outline-none focus:border-black"/></label><button onClick={save} className="mt-7 inline-flex items-center gap-2 rounded-full bg-black px-5 py-3 text-sm font-bold text-white"><Save size={16}/> Save profile</button></section><section className="rounded-3xl border border-black/10 bg-[#b7f23d] p-7"><Image src="/profile.png" width={500} height={500} alt="Profile" className="w-full rounded-2xl object-cover"/><p className="mt-5 text-sm font-bold">Profile image</p><p className="mt-1 text-xs leading-5 text-black/60">Replace <code>public/profile.png</code> to change the photo used across the site.</p></section></div> }
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-sm font-bold">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f8f8f5] p-3.5 outline-none focus:border-black"/></label>}

function ProjectsEditor({ projects, editing, project, setEditing, addProject, removeProject, updateProject }: {projects:Project[]; editing:string|null; project?:Project; setEditing:(x:string|null)=>void; addProject:()=>void; removeProject:(id:string)=>void; updateProject:(p:Project)=>void}) { return <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-3xl border border-black/10 bg-white p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-neutral-400">Content</p><h2 className="text-2xl font-bold">Projects</h2></div><button onClick={addProject} className="flex items-center gap-2 rounded-full bg-black px-4 py-2 text-xs font-bold text-white"><Plus size={15}/> Add</button></div><div className="space-y-2">{projects.map(p=><div key={p.id} className={`flex items-center gap-2 rounded-2xl border p-3 ${editing===p.id?'border-black bg-[#f4f4f0]':'border-black/10'}`}><button onClick={()=>setEditing(p.id)} className="min-w-0 flex-1 text-left"><p className="truncate font-bold">{p.title}</p><p className="text-xs text-neutral-500">{p.year} · {p.tech.slice(0,2).join(' · ')}</p></button><button onClick={()=>removeProject(p.id)} className="rounded-full p-2 text-neutral-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={16}/></button></div>)}</div></section>{project ? <ProjectForm project={project} updateProject={updateProject} close={()=>setEditing(null)}/> : <div className="flex min-h-[420px] items-center justify-center rounded-3xl border border-dashed border-black/20 bg-white p-8 text-center"><div><p className="font-display text-4xl font-bold">Select a project.</p><p className="mt-2 text-sm text-neutral-500">Or create a new one to start editing.</p></div></div>}</div> }
function ProjectForm({project,updateProject,close}:{project:Project;updateProject:(p:Project)=>void;close:()=>void}) { const [p,setP]=useState(project); useEffect(()=>setP(project),[project]); const set=(k:keyof Project,v:any)=>setP(x=>({...x,[k]:v})); const commit=()=>updateProject(p); return <section className="rounded-3xl border border-black/10 bg-white p-7"><div className="mb-7 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-neutral-400">Project editor</p><h2 className="mt-1 text-2xl font-bold">{p.title}</h2></div><button onClick={close} className="rounded-full p-2 hover:bg-black/5"><X size={18}/></button></div><div className="grid gap-5 md:grid-cols-2"><Field label="Title" value={p.title} onChange={v=>set('title',v)}/><Field label="Year" value={p.year} onChange={v=>set('year',v)}/></div><label className="mt-5 block text-sm font-bold">Description<textarea value={p.description} onChange={e=>set('description',e.target.value)} rows={4} className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f8f8f5] p-4 outline-none"/></label><label className="mt-5 block text-sm font-bold">Technologies <input value={p.tech.join(', ')} onChange={e=>set('tech',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))} className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f8f8f5] p-3.5 outline-none"/></label><label className="mt-5 block text-sm font-bold">Features <textarea value={p.features.join('\n')} onChange={e=>set('features',e.target.value.split('\n').filter(Boolean))} rows={5} className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f8f8f5] p-4 outline-none"/></label><div className="grid gap-5 md:grid-cols-2"><Field label="Live URL" value={p.liveUrl} onChange={v=>set('liveUrl',v)}/><Field label="GitHub URL" value={p.githubUrl} onChange={v=>set('githubUrl',v)}/></div><div className="mt-7 flex gap-3"><button onClick={commit} className="inline-flex items-center gap-2 rounded-full bg-black px-5 py-3 text-sm font-bold text-white"><Save size={16}/> Save project</button><button onClick={close} className="rounded-full border border-black/10 px-5 py-3 text-sm font-bold">Cancel</button></div></section> }

function SocialEditor({socials,updateSocial,save}:{socials:Social[];updateSocial:(id:string,f:keyof Social,v:string)=>void;save:()=>void}){return <section className="max-w-3xl rounded-3xl border border-black/10 bg-white p-7"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-neutral-400">Connections</p><h2 className="mt-1 text-2xl font-bold">Social links</h2><p className="mt-2 text-sm text-neutral-500">Edit the links shown in the contact section.</p></div><div className="space-y-4">{socials.map(s=><div key={s.id} className="rounded-2xl border border-black/10 p-5"><div className="mb-4 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f4f4f0]">{s.id==='github'?<Mail size={17}/>:s.id==='linkedin'?<Mail size={17}/>:s.id==='instagram'?<Mail size={17}/>:<Mail size={17}/>}</div><div><p className="font-bold">{s.label}</p><p className="text-xs text-neutral-400">{s.id}</p></div></div><div className="grid gap-4 md:grid-cols-2"><Field label="Label" value={s.label} onChange={v=>updateSocial(s.id,'label',v)}/><Field label="Handle" value={s.handle} onChange={v=>updateSocial(s.id,'handle',v)}/></div><label className="mt-4 block text-sm font-bold">URL<input value={s.url} onChange={e=>updateSocial(s.id,'url',e.target.value)} className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f8f8f5] p-3.5 outline-none"/></label></div>)}</div><button onClick={save} className="mt-7 inline-flex items-center gap-2 rounded-full bg-black px-5 py-3 text-sm font-bold text-white"><Save size={16}/> Save links</button></section>}
